sudo: false

language: python

# Source: https://github.com/rfk/pyenchant
matrix:
  include:
    - os: osx
      language: generic
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7

addons:
  apt:
    packages:
      - libenchant-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3 enchant; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv ./venv -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source ./venv/bin/activate; fi

install:
  - pip install -r requirements.txt

script:
  - pytest --cov=./

after_success:
  - codecov
