sudo: false

language: python

matrix:
  include:
    - os: osx
      language: generic
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7

addons:
  apt:
    packages:
      - libenchant-dev
    update: true
  homebrew:
    packages:
      - enchant
    update: true

install:
  - pip install -r requirements.txt
  - python -m nltk.downloader words

script:
  - pytest --cov=./

after_success:
  - codecov
