sudo: false

language: python
python:
  - 3.6
  - 3.7

matrix:
  include:
    - os: osx
      language: shell
      python: 3.6  # default available
      before_install:
        - pip install virtualenv
        - virtualenv ./venv -p python3
        - source ./venv/bin/activate
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
      after_success:
        - codecov

addons:
  apt:
    packages:
      - libenchant-dev
    update: true
  homebrew:
    packages:
      - enchant
    update: true

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov

install:
  - pip install -r requirements.txt
  - python -m nltk.downloader words

script:
  - pytest


