sudo: false

language: python

matrix:
  include:
    - os: osx
      language: shell
      python:
        - 3.6  # default available
      before_install:
        - pip install virtualenv
        - virtualenv ./venv -p python3
        - source ./venv/bin/activate
        - python --version
    - os: linux
      python:
        - 3.6
        - 3.7

addons:
  apt:
    packages:
      - libenchant-dev
    update: true
  homebrew:
    packages:
      - enchant
    update: true

install:
  - pip install -r requirements.txt codecov
  - python -m nltk.downloader words

script:
  - pytest

after_success:
  - codecov
