sudo: false

language: python

matrix:
  include:
    - os: osx
      language: generic
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7

addons:
  apt:
    packages:
      - libenchant-dev
    update: true
  homebrew:
    packages:
      - enchant
    update: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv ./venv -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source ./venv/bin/activate; fi

install:
  - pip install -r requirements.txt
  - python -m nltk.downloader words

script:
  - pytest --cov=./

after_success:
  - codecov
